config/routes.rb
Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  get 'screen' => 'screen#show'

  mount Blazer::Engine, at: 'analytics'

  resources :products, only: %i[index show]
  resources :variants, only: [] do
    resources :registrations, only: %i[new create]
  end
  resources :registrations, only: %i[index show] do
    member do
      get :collect
      get :confirm
    end
  end
  namespace :admin do
    get 'dashboard/index'
    get 'products/dashboard' => 'products/dashboard#index'
    resources :products
    resources :products, module: :products, only: [] do
      resources :registrations, only: [:index]
      resources :attendance, only: [:index]
    end
    resources :registrations, only: %i[index show] do
      patch :abandon, on: :member
      patch :cancel, on: :member
      patch :toggle_check_in, on: :member
    end
    resources :form_packets, shallow: true do
      resources :form_templates, shallow: true do
        resources :form_elements, except: %i[index show]
      end
    end
  end

  # redirect from legacy registrar routes
  get 'registrar/items/:id', to: redirect('/products/%<id>s')
  get 'registrar/items', to: redirect('/products')
  get 'registrar/admin(/*route)', to: redirect('/admin/products/dashboard')

  passwordless_for :users

  namespace :host do
    resources :visits, only: %i[index show]
    resources :events, only: %i[index show]
    resources :exceptions, only: :index
  end

  resources :stripe_connects, only: :create

  resources :chromecasts, only: :show

  get 'cast/index'

  get 'casts' => 'casts#index', :as => :casts
  get 'casts/:slug' => 'casts#show', :as => :cast

  unless Rails.env.production?
    resources :tenants, only: :index do
      put :select, on: :member
    end
  end

  get 'pack' => 'client#index'

  match 'markdown' => 'markdown#preview', :as => :markdown, :via => :post

  namespace :api do # rubocop:disable Metrics/BlockLength
    resources :tenants
    resources :events, only: [:index]
    resources :programs, only: [:index]
    resources :games, only: %i[index show] do
      get 'statify', on: :member
      put 'statify', on: :member
    end
    namespace :hockey do
      resources :statsheets, only: [:show]
      resources :goals, only: %i[create update]
    end
    namespace :general do
      resources :events, only: [] do
        match :batch_create, via: %i[post options], on: :collection
      end
    end
    namespace :league do
      resources :programs, only: [:index]
      resources :seasons, only: [:index]
      resources :divisions, only: [:index]
      resources :teams, only: [:index]
      resources :games do
        match :batch_create, via: %i[post options], on: :collection
      end
      resources :practices do
        match :batch_create, via: %i[post options], on: :collection
      end
      resources :players do
        match :batch_create, via: %i[post options], on: :collection
      end
    end
    resources :locations, only: [:index]
    resources :tags, only: %i[index update]
  end

  get 'game_result/edit'

  get 'game_result/update'

  get 'commish/index'

  resources :posts, only: [:show]

  get 'dashboard/index'

  root to: 'pages#show'

  resources :authentications

  match 'user/schedule' => 'users#schedule', via: :get, as: :user_schedule
  match 'user/teams' => 'users#teams', via: :get, as: :user_teams
  match 'user/subscribe' => 'users#subscribe', via: :post, as: :subscribe_user
  match 'users/:id/schedule' => 'users#schedule', via: :get, as: :users_schedule

  namespace :host do
    root to: 'dashboard#index'
    resources :tenants
    resources :users
    get 'status' => 'dashboard#status'
  end

  namespace :admin do
    root to: 'dashboard#index'

    get 'uploads(/*path)', to: 'uploads#index', as: :uploads

    resources :users, only: %i[index show update] do
      scope module: :users do
        resources :registrations, only: [:index]
        resources :teams, only: [:index]
        resources :vouchers, only: %i[index create]
      end
    end
  end

  resources :programs, only: %i[index show delete], param: :slug

  match 'schedule' => 'schedule#index', :as => :schedule, :via => :get

  match 'league/:league_slug/schedule/:division_slug' => 'league/schedule#index', :as => :league_schedule, :via => :get
  match 'league/:league_slug/scoreboard/:division_slug' => 'scoreboard#index', :as => :league_scoreboard, :via => :get
  match 'league/:league_slug/standings/:division_slug(/:season_slug)' => 'standings#index', :as => :league_standings,
        :via => :get
  match 'league/:league_slug/statistics/:division_slug(/:season_slug)' => 'statistics#index',
        :as => :league_statistics, :via => :get
  match 'league/:league_slug/statistics/:division_slug/:season_slug/:view' => 'statistics#show',
        :as => :league_statistic, :via => :get
  match 'league/:league_slug/teams/:division_slug(/:season_slug)' => 'league/teams#index', :as => :league_teams,
        :via => :get
  match 'league/:league_slug/teams/:division_slug/:season_slug/:team_slug/schedule' => 'league/teams#schedule',
        :as => :league_team_schedule, :via => :get
  match 'league/:league_slug/teams/:division_slug/:season_slug/:team_slug/roster' => 'league/teams#roster',
        :as => :league_team_roster, :via => :get
  match 'league/:league_slug/teams/:division_slug/:season_slug/:team_slug/statistics' => 'league/teams#statistics',
        :as => :league_team_statistics, :via => :get
  match 'league/:league_slug/players/:division_slug(/:season_slug)' => 'players#index', :as => :league_players,
        :via => :get
  match 'league/:league_slug/players/:division_slug/:season_slug/:team_slug/:player_slug/:id' => 'players#show',
        :as => :league_player, :via => :get
  match 'league/:league_slug/players/:division_slug/:season_slug/:team_slug/:player_slug/:id/career' => 'players#career',
        :as => :league_player_career, :via => :get
  match 'league/:league_slug/game/:id/box_score' => 'league/games#box_score', :as => :league_game_box_score,
        :via => :get

  resources :seasons, only: [], shallow: true do
    resources :teams, only: %i[new create edit update delete], module: :league
  end

  resources :cast, only: :index

  namespace :admin do # rubocop:disable Metrics/BlockLength
    resources :chromecasts, except: [:show]
    resources :screens, except: [:show]

    resources :programs, only: %i[index destroy]
    namespace :league do
      resources :programs, except: %i[index destroy], shallow: true do
        resources :divisions, except: [:show] do
          resources :teams, except: [:index] do
            resources :players, except: %i[index show]
          end
        end
        resources :seasons
      end
      resources :events, only: %i[new create edit update]
      resources :games, only: %i[index new create edit update]
      resources :practices, only: %i[new create edit update]
    end

    # resources :seasons, :only => [:index, :show, :create, :new, :edit, :update, :delete], :shallow => true do
    #   resources :divisions, :except => :index
    #   resources :teams, :except => :index do
    #     resources :players
    #   end
    # end

    resources :teams, only: :index
    # resources :events
    resources :games, only: [] do
      resource :result, controller: :game_result, only: %i[edit update]
      resource :statsheet, only: [:edit] do
        get 'print', on: :member
      end
    end

    resources :clubs
    resources :locations, shallow: true do
      resources :playing_surfaces, except: %i[index show]
      resources :locker_rooms, except: %i[index show]
    end

    resources :events, only: %i[index update destroy] do
      get :proto, on: :collection
    end
    namespace :events do
      resources :locker_rooms, only: [] do
        post :assign, on: :collection
      end
    end

    namespace :general do
      resources :events, only: %i[show new create edit update]
    end
    resources :game_imports do
      post 'complete', on: :member
    end
    resources :player_imports do
      post 'complete', on: :member
    end

    resources :hockey_statsheets, only: %i[edit update] do
      post 'post', on: :member
      post 'unpost', on: :member
      resources :players, controller: 'hockey_players' do
        post 'load', on: :collection
        post 'reload', on: :collection
      end
      resources :goals, controller: 'hockey_goals'
      resources :penalties, controller: 'hockey_penalties'
      resources :goaltenders, controller: 'hockey_goaltenders' do
        post 'autoload', on: :collection
      end
    end

    # resources :standings_layouts do
    #  get 'columns', :on => :member
    #  resources :standings_columns do
    #    post 'push_left', :on => :member
    #    post 'push_right', :on => :member
    #  end
    # end
  end

  # match "admin/seasons(/:id)" => "admin/seasons#show", :as => :admin_seasons, :via => :get

  match 'admin/game_results' => 'admin/games/results#index', :as => :admin_game_results, :via => :get

  resources :pages, except: [:show] do
    member do
      post :move_up
      post :move_down
    end
    resources :sections, only: %i[create destroy] do
      post 'position', on: :collection
    end
    resources :blocks do
      post 'position', on: :collection
    end
    namespace :blocks do # :except => [:edit, :update] do
      resources :contacts, only: %i[edit update]
      resources :texts, only: %i[edit update]
      resources :images, only: %i[edit update]
      resources :feeds, only: %i[edit update]
      resources :documents, only: %i[edit update]
      resources :markups, only: %i[edit update]
      resources :carousels, only: %i[edit update]
      resources :event_feeds, only: %i[edit update]
    end
  end

  get '/pages/*path', to: 'pages#show', as: :page_friendly, via: :get

  namespace :admin do
    resources :posts
  end

  namespace :next do
    namespace :admin do
      root to: 'dashboard#index'
      namespace :events do

app/models/hockey_goaltender.rb
class HockeyGoaltender
  include Mongoid::Document
  include League::Sides

  field :plr

  field :min_1, :type => Integer, :default => 0
  field :min_2, :type => Integer, :default => 0
  field :min_3, :type => Integer, :default => 0
  field :min_ot, :type => Integer, :default => 0
  def min_total
    min_1 + min_2 + min_3 + min_ot
  end

  field :shots_1, :type => Integer, :default => 0
  field :shots_2, :type => Integer, :default => 0
  field :shots_3, :type => Integer, :default => 0
  field :shots_ot, :type => Integer, :default => 0
  def shots_total
    shots_1 + shots_2 + shots_3 + shots_ot
  end

  field :goals_1, :type => Integer, :default => 0
  field :goals_2, :type => Integer, :default => 0
  field :goals_3, :type => Integer, :default => 0
  field :goals_ot, :type => Integer, :default => 0
  def goals_total
    goals_1 + goals_2 + goals_3 + goals_ot
  end

  def saves_total
    shots_total - goals_total
  end

  def save_percentage
    saves_total.to_f / shots_total.to_f
  end

  embedded_in :hockey_scoresheet

  validates_presence_of :plr
  validates_numericality_of :min_1, :min_2, :min_3, :min_ot


end

app/controllers/admin/hockey_goaltenders_controller.rb
class Admin::HockeyGoaltendersController < Admin::BaseLeagueController
  skip_before_action :verify_admin
  before_action :verify_admin_or_operations
  before_action :find_statsheet
  before_action :find_goaltender, only: %i[edit update destroy]
  before_action :list_players, only: %i[new edit]

  def new
    @goaltender = @statsheet.goaltenders.build
  end

  def edit; end

  def update
    if @goaltender.update(hockey_goaltender_params)
      respond_to do |format|
        format.html do
          @statsheet.reload
          flash[:notice] = 'Goaltender Updated'
        end
        format.json { render json: @goaltender }
      end
    else
      respond_to do |format|
        format.html do
          list_players
        end
        format.json { render json: @goaltender.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @goaltender = @statsheet.goaltenders.build(hockey_goaltender_params)
    if @goaltender.save
      respond_to do |format|
        format.html do
          @statsheet.reload
          flash[:notice] = 'Goaltender Added'
        end
        format.json { render json: @goaltender }
      end
    else
      respond_to do |format|
        format.html do
          list_players
        end
        format.json { render json: @goaltender.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @goaltender.delete
      respond_to do |format|
        format.html { flash[:notice] = 'Goaltender has been deleted' }
        format.json { head :ok }
      end
    else
      respond_to do |format|
        format.html { flash[:error] = 'Goaltender could not be' }
        format.json { head :bad_request }
      end
    end
  end

  def autoload
    @statsheet.goaltenders.each(&:delete)
    @statsheet.autoload_goaltenders
    if @statsheet.save
      respond_to do |format|
        format.html do
          @statsheet.reload
          flash[:notice] = 'Goaltenders Loaded.'
        end
        format.json { render json: @statsheet.goaltenders.reload }
      end
    else
      respond_to do |format|
        format.html { flash[:error] = 'Goaltenders could not be loaded.' }
        format.json { head :bad_request }
      end
    end
  end

  private

  def hockey_goaltender_params
    params.required(:hockey_goaltender_result).permit(:team_id, :player_id, :minutes_played, :shots_against,
                                                      :goals_against)
  end

  def find_statsheet
    @statsheet = Hockey::Statsheet.find(params['hockey_statsheet_id'])
  end

  def find_goaltender
    @goaltender = @statsheet.goaltenders.find(params['id'])
  end

  def list_players
    @players = @statsheet.skaters.playing.order(last_name: :asc)
  end
end

app/views/admin/hockey_goaltenders/_edit.html.haml
= render :partial => 'admin/hockey_goaltenders/form', :locals => { :url => admin_hockey_statsheet_goaltender_path(@statsheet.id, @goaltender) }

app/views/admin/hockey_goaltenders/_form.html.haml
- edit_mode = ['edit','update'].index(params[:action]) ? true : false
= simple_form_for( @goaltender, :url => url, :remote => true ) do |f|
  = f.input :team_id, :collection => @statsheet.teams, :disabled => edit_mode, :label => 'Team'
  = f.input :player_id do
    = f.select :player_id, @players.map { |p| [ "#{p.jersey_number} - #{p.last_name}, #{p.first_name}", p.player_id, { :'data-team-id' => p.team_id }] }, { :include_blank => true }, { :class => 'form-control' }
  = f.input :minutes_played, :maxlength => 3, :pattern => "[0-9]*"
  = f.input :shots_against, :maxlength => 2, :pattern => "[0-9]*"
  = f.input :goals_against, :maxlength => 2, :pattern => "[0-9]*"
:javascript
  function filter_players(changed) {
    var teamId = $('select#hockey_goaltender_result_team_id').val();
    $('#hockey_goaltender_result_player_id option').hide().each(function(index, item){
      if(index > 0 && $(item).parent('span').length == 0) {
        $(item).wrap('<span style="display: none;" />');
      }
    });
    if (changed) {
      $('#hockey_goaltender_result_player_id').val('');
    }
    if (teamId != '') {
      $('#hockey_goaltender_result_player_id option[data-team-id=' + teamId + ']').show().unwrap();
    }
  }
  $(document).ready(function(){
    filter_players();
    $("select#hockey_goaltender_result_team_id").change(function(){
        filter_players(true);
    });
  });

app/views/admin/hockey_goaltenders/_list.html.haml
- if goaltenders.count == 0
  No goaltenders have been entered
- else
  %table.ui.celled.striped.table
    %thead
      %tr
        %th Team
        %th Player
        %th Minutes
        %th Shots
        %th Goals
        %th
    %tbody
      - goaltenders.each_with_index do |g, i|
        %tr
          %td= g.team.short_name
          %td= "#{g.jersey_number} - #{g.last_name}"
          %td= g.minutes_played
          %td= g.shots_against
          %td= g.goals_against
          %td.collapsing
            = link_to 'Edit', edit_admin_hockey_statsheet_goaltender_path(@statsheet, g), remote: true, class: [:ui, :primary, :mini, :button]
            = link_to 'Delete', admin_hockey_statsheet_goaltender_path(@statsheet, g), remote: true, confirm: 'Are you sure?', method: :delete, remote: true, confirm: 'Are you sure?', method: :delete, title: 'Delete this goal', class: [:ui, :primary, :mini, :button]

app/views/admin/hockey_goaltenders/_new.html.haml
= render :partial => 'admin/hockey_goaltenders/form', :locals => { :url => admin_hockey_statsheet_goaltenders_path(@statsheet.id) }

app/views/admin/hockey_goaltenders/autoload.js.erb
$("#flash_notice").html("<%= escape_javascript( flash.discard(:notice) )%>");
$("#flash_notice").show(300);
$("#goaltenders").html("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/list", :locals => { :goaltenders => @statsheet.goaltenders } ) )%>");

app/views/admin/hockey_goaltenders/create.js.erb
<% if @goaltender.errors.any? %>
  $("#flash_notice").hide(300);
  $('#dialog-modal').html("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/new" ) )%>");
<% else %>
  $("#flash_notice").html("<%= escape_javascript( flash.discard(:notice) )%>");
  $("#flash_notice").show(300);
  $("#goaltenders").html("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/list", :locals => { :goaltenders => @statsheet.goaltenders } ) )%>");
  $('#dialog-modal').dialog("close");
<% end %>

app/views/admin/hockey_goaltenders/destroy.js.erb
$("#flash_notice").html("<%= escape_javascript( flash.discard(:notice) )%>");
$("#flash_notice").show(300);
$("#goaltenders table").replaceWith("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/list", :locals => { :goaltenders => @statsheet.goaltenders } ) )%>");

app/views/admin/hockey_goaltenders/edit.js.erb
$('#dialog-modal').html("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/edit" ) )%>");
$('#dialog-modal').dialog({
  title: 'Edit Goaltender',
  height: 440,
  width: 500,
  modal: true,
  buttons: {
    Save: function() {
      $(this).children("form").submit();
    },
    Cancel: function() {
      $(this).dialog("close");
    }
  }
});

app/views/admin/hockey_goaltenders/new.js.erb
$('#dialog-modal').html("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/new" ) )%>");
$('#dialog-modal').dialog({
  title: 'Add Goaltender',
  height: 420,
  width: 500,
  modal: true,
  buttons: {
    Save: function() {
      $(this).children("form").submit();
    },
    Cancel: function() {
      $(this).dialog("close");
    }
  }
});

app/views/admin/hockey_goaltenders/update.js.erb
<% if @goaltender.errors.any? %>
  $("#flash_notice").hide(300);
  $('#dialog-modal').html("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/edit" ) )%>");
<% else %>
  $("#flash_notice").html("<%= escape_javascript( flash.discard(:notice) )%>");
  $("#flash_notice").show(300);
  $("#goaltenders table").replaceWith("<%= escape_javascript( render(:partial => "admin/hockey_goaltenders/list", :locals => { :goaltenders => @statsheet.goaltenders } ) )%>");
  $('#dialog-modal').dialog("close");
<% end %>